include ../common.mk

# Set the target binary files
TARGETS := bcf_add_line
# Set the xSqueezeIt object files required
XOBJS := ${XSQUEEZEITPATH}/xcf.o ${XSQUEEZEITPATH}/bcf_traversal.o

include ../common_rules.mk
