include ../common.mk

# Set the target binary files
TARGETS := analyze_bin bin_diff bin_splitter bin_merger bin_compare vertical_bin_merger
# Set the xSqueezeIt object files required
XOBJS := ${XSQUEEZEITPATH}/xcf.o ${XSQUEEZEITPATH}/bcf_traversal.o

include ../common_rules.mk