FROM ubuntu:20.04

MAINTAINER Rick Wertenbroek <rick.wertenbroek@unil.ch>

ENV DEBIAN_FRONTEND noninteractive

# Install required software and clean as not to make the layer dirty
RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	apt-utils curl gnupg gcc g++ make autoconf && \
	apt-get clean && apt-get purge && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	git zlib1g-dev libbz2-dev liblzma-dev && \
	apt-get clean && apt-get purge && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN apt-get update && apt-get -y upgrade && apt-get install -y \
	bcftools samtools unzip && \
	apt-get clean && apt-get purge && \
	rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# https://github.com/samtools/htslib/blob/f68c84ff46a63fde05ae2bdf3ebdec568c9c4613/cram/cram_io.c#L2923
COPY hts-ref.zip /root/.cache/

RUN cd /root/.cache/ && unzip hts-ref.zip && rm -f hts-ref.zip

# Clone Source Code Repository (with read-only token, TODO : change because it expires !)
RUN mkdir -p /usr/src/ && \
    cd /usr/src/ && \
    git clone https://rwk-unil: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@github.com/rwk-unil/pp.git && \
    cd /usr/src/pp && \
    cd Docker && \
    chmod +x *.sh && \
    ./prepare.sh

RUN cd /usr/src/pp/Docker && \
    ./build_install.sh

# Work in this temporary directory
WORKDIR /tmp/work

CMD echo "Run with the following command : docker run <tag> <command> [args]"