#!/bin/bash
# pp-toolkit-builder 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {
    echo "Value of label: '$label'"

    # Clone and build the tools
    git clone https://github.com/rwk-unil/pp.git
    cd pp
    ./prepare_build.sh

    # Bootstrap so that the builder can auto update how it builds
    source ./dnanexus_app/pp-toolkit-builder/src/bootstrap.sh
}
