include ../common.mk

# Set the target binary files
TARGETS := pp_extract pp_show
# Set the xSqueezeIt object files required
XOBJS := ${XSQUEEZEITPATH}/xcf.o ${XSQUEEZEITPATH}/bcf_traversal.o

include ../common_rules.mk
