include ../common.mk

# Set the target binary files
TARGETS := phase_caller phase_caller2
# Set the xSqueezeIt object files required
XOBJS := ${XSQUEEZEITPATH}/xcf.o ${XSQUEEZEITPATH}/bcf_traversal.o

include ../common_rules.mk
